Refactor + bug fix table plane extractor
v4r-tuwien/table_plane_extractor pull request #7
Opened 2023-11-30 15:28 UTC by haberger

2023-12-05 19:00 UTC, lexihaberl requested changes

2023-12-05 19:00 UTC, lexihaberl commented on src/__pycache__/table_plane_extractor.cpython-38.pyc
We should remove the .pyc stuff

2023-12-05 19:00 UTC, lexihaberl commented on src/extractor_of_table_objects.py
> +    print(height*width)
Remove the print statements.

2023-12-05 19:00 UTC, lexihaberl commented on src/extractor_of_table_objects.py
> +def extract_objects_from_tableplane(pcd, table_planes, eps, min_points, min_volume, max_obj_height, height, width):
Add a docstring that documents the types of the input and output arguments

2023-12-05 19:00 UTC, lexihaberl commented on src/extractor_of_table_objects.py
> +        print(np.asarray(scene_above_table.points).shape)
Remove print

2023-12-05 19:00 UTC, lexihaberl commented on src/extractor_of_table_objects.py
> +        print(labels_unique)
Remove print

2023-12-05 19:00 UTC, lexihaberl commented on src/extractor_of_table_planes.py
> +    #o3d.io.write_point_cloud("/root/HSR/catkin_ws/test_as.pcd", pcd)
remove

2023-12-05 19:00 UTC, lexihaberl commented on src/extractor_of_table_planes.py
> +        list: List of oriented bounding boxes (Open3D geometry objects) around the detected planes.
Write the actual type (open3d.geometry.OrientedBoundingBox) instead of (Open3D geometry object)

2023-12-05 19:00 UTC, lexihaberl commented on src/extractor_of_table_planes.py
> +        if counts[label] < 70:
Maybe make this a parameter?

2023-12-05 19:00 UTC, lexihaberl commented on src/extractor_of_table_planes.py
> +        min_points=min_cluster_size))
Maybe describe why we do this preclustering instead of writing a comment that has exactly the same information as the line of code below it.

2023-12-05 19:00 UTC, lexihaberl commented on src/table_objects_extractor_as.py
> +import numpy as np
Some imports occur more than once

2023-12-05 19:00 UTC, lexihaberl commented on README.md
Also add the topics + message types of the visualization messages.

2023-12-05 19:00 UTC, lexihaberl commented on src/table_objects_extractor_as.py
> +        Topic: /objects_on_table/get_labels_img
Update to new topic name

2023-12-05 19:00 UTC, lexihaberl commented on src/table_objects_extractor_srv.py
> +def table_objects_extractor(pcd): #TODO remove target frame also from config
Remove param from config and then the TODO

2023-12-05 19:00 UTC, lexihaberl commented on src/table_objects_extractor_srv.py
> +    print("Ready to detect objects on table plane.")
rospy.loginfo instead

2023-12-05 19:00 UTC, lexihaberl commented on src/table_plane_extractor_srv.py
> +        '/test/table_plane_extractor',
We should probably also update this service name. Maybe /table_plane_extractor/get_planes or something like that?

2023-12-05 19:00 UTC, lexihaberl commented on src/table_plane_extractor_srv.py
> +        '/test/table_plane_extractor',
Dont forget to update the readme as well.

2023-12-05 19:00 UTC, lexihaberl commented on src/testscripts/table_objects_extractor_as_testscript.py
You should probably also clean this file, as the testscripts can be used as a baseline if you want to use the code for your project. The variable names should be more specific: e.g. table_object_extractor instead of detector_pose_estimator.
Maybe also add a sentence in the README that states that the testscripts can be used as a template/boilerplate

2023-12-07 12:48 UTC, haberger commented on src/__pycache__/table_plane_extractor.cpython-38.pyc
danke ceder

2023-12-18 22:21 UTC, lexihaberl approved these changes
LGTM

2023-12-18 22:25 UTC, merged